[package]
name = "bod"
version = "0.1.0"
authors = ["felipe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.10.4", features = ["blocking"]}
clap = "2.33.1"
serde_json = "1.0.53"